### ISSUE TITLE
RBAC permissions include secret delete?

### ISSUE THREAD

**Issue by coderanger** [machinezone/configmapsecrets#3]
Looking through the code, it doesn't look like this is used, maybe just an oversight?

**Comment by coderanger** [comment]
In general the requested RBAC permissions seem a lot bigger than what is actually used.

**Comment by abursavich** [comment]
IIRC, the purpose of that was to delete the generated Secret when its associated ConfigMapSecret is deleted, similar to how deleting a Deployment would cause its Pods to be removed.

I'll take another look when I have a chance. Garbage collection may be taken care of by the apiserver without the controller needing that access now.

**Comment by coderanger** [comment]
That's handled automatically as you mentioned. You only need to request permissions for the API calls you actually make. I'm still kicking the tires but this is what I have so far:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmapsecrets
rules:
- apiGroups: [""]
  resources: [configmaps, secrets]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, update]
- apiGroups: [secrets.mz.com]
  resources: [configmapsecrets]
  verbs: [get, list, watch]
- apiGroups: [secrets.mz.com]
  resources: [configmapsecrets/status]
  verbs: [get, patch, update]
```
